language: python
python:
- '3.7'
env:
  global:
  - COMMIT_AUTHOR_EMAIL=travis-ci@w3.org
install:
- git clone --depth=1 --branch=master https://github.com/tabatkins/bikeshed.git ./bikeshed
- pip install pygments
- pip install --upgrade setuptools
- pip install --editable ./bikeshed
- bikeshed update
script:
- mkdir out
- bikeshed spec index.bs out/index.html
- cp document-policy.redirect.html out/document-policy.html
before_deploy:
- openssl aes-256-cbc -K $encrypted_b330ad4127a4_key -iv $encrypted_b330ad4127a4_iv
  -in deploy_key.enc -out deploy_key -d
deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    branch: master
